### ISSUE TITLE
freezing issues

### ISSUE THREAD

**Issue by BopOSRS** [Mrnice98/BossingInfo#11]
took me a while to figure out this plugin was the cause, and i've tried a few things to fix it but idk

Past few months when using this plugin every so often the client will just completely freeze for up to 20 seconds when I get a kill on a boss, I couldn't find anything in the logs to figure out what was causing it so figured I'd just post this here

i tried uninstalling and reinstalling from RL but that didn't fix it, idk if there's other ways to completely remove it or smth

**Comment by Mrnice98** [comment]
I will look into this when I have time, but I've not gotten any other reports of this until now.

**Comment by Reeenatu** [comment]
Wow, this is exactly whats happening to me, it been like this since a long long time back when i was hunting smoke devil boss back in May 2023 (dk if it helps).

**Comment by beeznutzz** [comment]
I also have the problem, ever time i kill vardorvis my client freezes and i have to go on task manager to close the client. They really unfortunate part is i loose any drop i get since its an instance boss.

**Comment by beeznutzz** [comment]
i ended up just removing the plugin and it doesnt freeze anymore.i would love if you can fix and i can use plugin again!

**Comment by Mrnice98** [comment]
this is clearly more widespread issue at this point and is going to be looked at shortly. I cannot recreate this on my own system so I am reliant on logs and testing from those affected.
