### ISSUE TITLE
Thermy Boss Gp/Hr doesn't work as it isn't tracking drops correctly

### ISSUE THREAD

**Issue by pwatts6060** [Mrnice98/BossingInfo#17]
![image](https://github.com/Mrnice98/BossingInfo/assets/30028569/330b7acc-9932-48cf-9455-6d37ba1b199d)
It has the loot from 1 kree'arra kill I did just before. I believe it's because the loot spawns in a weird place not where the boss is usually.

**Comment by Mrnice98** [comment]
I will see if I can recreate this. Please re-open issue if its persisting.
