### ISSUE TITLE
onChatMessage on login screen crashes client

### ISSUE THREAD

**Issue by pwatts6060** [Mrnice98/BossingInfo#2]
If another plugin sends a chat message when the client is on the login screen, this plugin causes runelite to crash. 

Noticed this when working on the Shooting Star Tracking plugin if you import malformed data (probably normal data to). 

```
2022-07-10 02:31:21 [Client] ERROR net.runelite.client.RuneLite - Uncaught exception:
java.lang.AssertionError: null
	at com.killsperhour.KphPlugin.onChatMessage(KphPlugin.java:334)
```

**Comment by Mrnice98** [comment]
plugin is being updated to reflect this change
