### ISSUE TITLE
Plugin deleted from hub/my plugins?

### ISSUE THREAD

**Issue by 99Doobies** [Mrnice98/BossingInfo#7]
Plugin is no longer in the hub, not sure if this is intended or a a bug, figured this doesnt hurt.

**Comment by YvesW** [comment]
The plugin failed to build, as can be seen here: https://github.com/runelite/plugin-hub/actions/runs/4074193860/jobs/7019034539

**Comment by YvesW** [comment]
@99Doobies The PR hasn't been merged yet, so you shouldn't close the issue yet.
